### ISSUE TITLE
User Folder

### ISSUE THREAD

**Issue by TassLehoff** [ExplodyCat/octgnNetImages#4]
My user folder is not in C:\user but in D:\user, so this is not working.

**Comment by ExplodyCat** [comment]
Hey @TassLehoff , try putting the program in the root of your octgn folder then on command line run octgnNetImages.exe -c

**Comment by TassLehoff** [comment]
Thanks for your answer, i closed the issue because i find by myself the -c
cmd ^^

In fact i'm the maintainer of agot on octgn, so if you need something tell
me ;)

See ya
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Cet
e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-29 19:44 GMT+01:00 Jerry notifications@github.com:
